/** Top 3 most-searched codes per brand — prose-linked from brand hub intro (S1.4). */
export const brandTopCodes: Record<string, readonly [string, string, string]> = {
  goodman: ["4-flash", "e0", "e3"],
  carrier: ["33", "14", "13"],
  lennox: ["270", "200", "201"],
  trane: ["3-flashes", "4-flashes", "2-flashes"],
  rheem: ["33", "10", "11"],
  bryant: ["33", "14", "13"],
  york: ["3-blinks", "4-blinks", "1-blink"],
  amana: ["4-flash", "e0", "e3"],
  ruud: ["33", "10", "11"],
  "american-standard": ["3-flashes", "4-flashes", "2-flashes"],
  heil: ["4-flash", "3-flash", "2-flash"],
  payne: ["33", "14", "13"],
  tempstar: ["4-flash", "3-flash", "2-flash"],
  coleman: ["4-blinks", "3-blinks", "5-blinks"],
  luxaire: ["3-blinks", "4-blinks", "1-blink"],
  "armstrong-air": ["270", "200", "201"],
  daikin: ["4-flash", "e0", "e3"],
  comfortmaker: ["4-flash", "3-flash", "2-flash"],
  keeprite: ["4-flash", "3-flash", "2-flash"],
  "day-and-night": ["4-flash", "3-flash", "2-flash"],
  intertherm: ["4-blinks", "2-blinks", "1-blink"],
  miller: ["4-blinks", "2-blinks", "1-blink"],
};
